export const serverCoreCoverageAllowlist = [
	"src/server/api-cache.ts",
	"src/server/download-manager.ts",
	"src/server/download-clients/http.ts",
	"src/server/download-clients/qbittorrent.ts",
	"src/server/download-clients/registry.ts",
	"src/server/download-clients/sabnzbd.ts",
	"src/server/hint-extractor.ts",
	"src/server/image-cache.ts",
	"src/server/import-mapping.ts",
	"src/server/indexers/http.ts",
	"src/server/indexers/release-type-parser.ts",
	"src/server/settings-store.ts",
	"src/server/settings-value.ts",
	"src/server/users.ts",
	"src/lib/runtime.ts",
	"src/lib/table-column-defaults.ts",
] as const;
