/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSearchRouteImport } from './routes/_authed/search'
import { Route as AuthedLibraryRouteImport } from './routes/_authed/library'
import { Route as AuthedHistoryRouteImport } from './routes/_authed/history'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedBooksIndexRouteImport } from './routes/_authed/books/index'
import { Route as AuthedAuthorsIndexRouteImport } from './routes/_authed/authors/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSettingsRootFoldersRouteImport } from './routes/_authed/settings/root-folders'
import { Route as AuthedSettingsProfilesRouteImport } from './routes/_authed/settings/profiles'
import { Route as AuthedSettingsGeneralRouteImport } from './routes/_authed/settings/general'
import { Route as AuthedBooksBookIdRouteImport } from './routes/_authed/books/$bookId'
import { Route as AuthedAuthorsAuthorIdRouteImport } from './routes/_authed/authors/$authorId'
import { Route as AuthedAddBookRouteImport } from './routes/_authed/add/book'
import { Route as AuthedAddAuthorRouteImport } from './routes/_authed/add/author'
import { Route as AuthedHardcoverAuthorsAuthorSlugRouteImport } from './routes/_authed/hardcover/authors/$authorSlug'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSearchRoute = AuthedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLibraryRoute = AuthedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHistoryRoute = AuthedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBooksIndexRoute = AuthedBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuthorsIndexRoute = AuthedAuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRootFoldersRoute =
  AuthedSettingsRootFoldersRouteImport.update({
    id: '/settings/root-folders',
    path: '/settings/root-folders',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSettingsProfilesRoute = AuthedSettingsProfilesRouteImport.update({
  id: '/settings/profiles',
  path: '/settings/profiles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsGeneralRoute = AuthedSettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBooksBookIdRoute = AuthedBooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuthorsAuthorIdRoute = AuthedAuthorsAuthorIdRouteImport.update({
  id: '/authors/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAddBookRoute = AuthedAddBookRouteImport.update({
  id: '/add/book',
  path: '/add/book',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAddAuthorRoute = AuthedAddAuthorRouteImport.update({
  id: '/add/author',
  path: '/add/author',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHardcoverAuthorsAuthorSlugRoute =
  AuthedHardcoverAuthorsAuthorSlugRouteImport.update({
    id: '/hardcover/authors/$authorSlug',
    path: '/hardcover/authors/$authorSlug',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/history': typeof AuthedHistoryRoute
  '/library': typeof AuthedLibraryRoute
  '/search': typeof AuthedSearchRoute
  '/add/author': typeof AuthedAddAuthorRoute
  '/add/book': typeof AuthedAddBookRoute
  '/authors/$authorId': typeof AuthedAuthorsAuthorIdRoute
  '/books/$bookId': typeof AuthedBooksBookIdRoute
  '/settings/general': typeof AuthedSettingsGeneralRoute
  '/settings/profiles': typeof AuthedSettingsProfilesRoute
  '/settings/root-folders': typeof AuthedSettingsRootFoldersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/authors/': typeof AuthedAuthorsIndexRoute
  '/books/': typeof AuthedBooksIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/hardcover/authors/$authorSlug': typeof AuthedHardcoverAuthorsAuthorSlugRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/history': typeof AuthedHistoryRoute
  '/library': typeof AuthedLibraryRoute
  '/search': typeof AuthedSearchRoute
  '/': typeof AuthedIndexRoute
  '/add/author': typeof AuthedAddAuthorRoute
  '/add/book': typeof AuthedAddBookRoute
  '/authors/$authorId': typeof AuthedAuthorsAuthorIdRoute
  '/books/$bookId': typeof AuthedBooksBookIdRoute
  '/settings/general': typeof AuthedSettingsGeneralRoute
  '/settings/profiles': typeof AuthedSettingsProfilesRoute
  '/settings/root-folders': typeof AuthedSettingsRootFoldersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/authors': typeof AuthedAuthorsIndexRoute
  '/books': typeof AuthedBooksIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/hardcover/authors/$authorSlug': typeof AuthedHardcoverAuthorsAuthorSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/history': typeof AuthedHistoryRoute
  '/_authed/library': typeof AuthedLibraryRoute
  '/_authed/search': typeof AuthedSearchRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/add/author': typeof AuthedAddAuthorRoute
  '/_authed/add/book': typeof AuthedAddBookRoute
  '/_authed/authors/$authorId': typeof AuthedAuthorsAuthorIdRoute
  '/_authed/books/$bookId': typeof AuthedBooksBookIdRoute
  '/_authed/settings/general': typeof AuthedSettingsGeneralRoute
  '/_authed/settings/profiles': typeof AuthedSettingsProfilesRoute
  '/_authed/settings/root-folders': typeof AuthedSettingsRootFoldersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/authors/': typeof AuthedAuthorsIndexRoute
  '/_authed/books/': typeof AuthedBooksIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/hardcover/authors/$authorSlug': typeof AuthedHardcoverAuthorsAuthorSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/history'
    | '/library'
    | '/search'
    | '/add/author'
    | '/add/book'
    | '/authors/$authorId'
    | '/books/$bookId'
    | '/settings/general'
    | '/settings/profiles'
    | '/settings/root-folders'
    | '/api/auth/$'
    | '/authors/'
    | '/books/'
    | '/settings/'
    | '/hardcover/authors/$authorSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/history'
    | '/library'
    | '/search'
    | '/'
    | '/add/author'
    | '/add/book'
    | '/authors/$authorId'
    | '/books/$bookId'
    | '/settings/general'
    | '/settings/profiles'
    | '/settings/root-folders'
    | '/api/auth/$'
    | '/authors'
    | '/books'
    | '/settings'
    | '/hardcover/authors/$authorSlug'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/history'
    | '/_authed/library'
    | '/_authed/search'
    | '/_authed/'
    | '/_authed/add/author'
    | '/_authed/add/book'
    | '/_authed/authors/$authorId'
    | '/_authed/books/$bookId'
    | '/_authed/settings/general'
    | '/_authed/settings/profiles'
    | '/_authed/settings/root-folders'
    | '/api/auth/$'
    | '/_authed/authors/'
    | '/_authed/books/'
    | '/_authed/settings/'
    | '/_authed/hardcover/authors/$authorSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/search': {
      id: '/_authed/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthedSearchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library': {
      id: '/_authed/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthedLibraryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/history': {
      id: '/_authed/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthedHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/books/': {
      id: '/_authed/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof AuthedBooksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/authors/': {
      id: '/_authed/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthedAuthorsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings/root-folders': {
      id: '/_authed/settings/root-folders'
      path: '/settings/root-folders'
      fullPath: '/settings/root-folders'
      preLoaderRoute: typeof AuthedSettingsRootFoldersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/profiles': {
      id: '/_authed/settings/profiles'
      path: '/settings/profiles'
      fullPath: '/settings/profiles'
      preLoaderRoute: typeof AuthedSettingsProfilesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/general': {
      id: '/_authed/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthedSettingsGeneralRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/books/$bookId': {
      id: '/_authed/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AuthedBooksBookIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/authors/$authorId': {
      id: '/_authed/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthedAuthorsAuthorIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/add/book': {
      id: '/_authed/add/book'
      path: '/add/book'
      fullPath: '/add/book'
      preLoaderRoute: typeof AuthedAddBookRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/add/author': {
      id: '/_authed/add/author'
      path: '/add/author'
      fullPath: '/add/author'
      preLoaderRoute: typeof AuthedAddAuthorRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/hardcover/authors/$authorSlug': {
      id: '/_authed/hardcover/authors/$authorSlug'
      path: '/hardcover/authors/$authorSlug'
      fullPath: '/hardcover/authors/$authorSlug'
      preLoaderRoute: typeof AuthedHardcoverAuthorsAuthorSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedHistoryRoute: typeof AuthedHistoryRoute
  AuthedLibraryRoute: typeof AuthedLibraryRoute
  AuthedSearchRoute: typeof AuthedSearchRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAddAuthorRoute: typeof AuthedAddAuthorRoute
  AuthedAddBookRoute: typeof AuthedAddBookRoute
  AuthedAuthorsAuthorIdRoute: typeof AuthedAuthorsAuthorIdRoute
  AuthedBooksBookIdRoute: typeof AuthedBooksBookIdRoute
  AuthedSettingsGeneralRoute: typeof AuthedSettingsGeneralRoute
  AuthedSettingsProfilesRoute: typeof AuthedSettingsProfilesRoute
  AuthedSettingsRootFoldersRoute: typeof AuthedSettingsRootFoldersRoute
  AuthedAuthorsIndexRoute: typeof AuthedAuthorsIndexRoute
  AuthedBooksIndexRoute: typeof AuthedBooksIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedHardcoverAuthorsAuthorSlugRoute: typeof AuthedHardcoverAuthorsAuthorSlugRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedHistoryRoute: AuthedHistoryRoute,
  AuthedLibraryRoute: AuthedLibraryRoute,
  AuthedSearchRoute: AuthedSearchRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAddAuthorRoute: AuthedAddAuthorRoute,
  AuthedAddBookRoute: AuthedAddBookRoute,
  AuthedAuthorsAuthorIdRoute: AuthedAuthorsAuthorIdRoute,
  AuthedBooksBookIdRoute: AuthedBooksBookIdRoute,
  AuthedSettingsGeneralRoute: AuthedSettingsGeneralRoute,
  AuthedSettingsProfilesRoute: AuthedSettingsProfilesRoute,
  AuthedSettingsRootFoldersRoute: AuthedSettingsRootFoldersRoute,
  AuthedAuthorsIndexRoute: AuthedAuthorsIndexRoute,
  AuthedBooksIndexRoute: AuthedBooksIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedHardcoverAuthorsAuthorSlugRoute: AuthedHardcoverAuthorsAuthorSlugRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
