/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedAuthorsIndexRouteImport } from './routes/_authed/authors/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSettingsRootFoldersRouteImport } from './routes/_authed/settings/root-folders'
import { Route as AuthedSettingsProfilesRouteImport } from './routes/_authed/settings/profiles'
import { Route as AuthedSettingsGeneralRouteImport } from './routes/_authed/settings/general'
import { Route as AuthedAuthorsAuthorIdRouteImport } from './routes/_authed/authors/$authorId'
import { Route as AuthedAddAuthorRouteImport } from './routes/_authed/add/author'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuthorsIndexRoute = AuthedAuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRootFoldersRoute =
  AuthedSettingsRootFoldersRouteImport.update({
    id: '/settings/root-folders',
    path: '/settings/root-folders',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSettingsProfilesRoute = AuthedSettingsProfilesRouteImport.update({
  id: '/settings/profiles',
  path: '/settings/profiles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsGeneralRoute = AuthedSettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuthorsAuthorIdRoute = AuthedAuthorsAuthorIdRouteImport.update({
  id: '/authors/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAddAuthorRoute = AuthedAddAuthorRouteImport.update({
  id: '/add/author',
  path: '/add/author',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/add/author': typeof AuthedAddAuthorRoute
  '/authors/$authorId': typeof AuthedAuthorsAuthorIdRoute
  '/settings/general': typeof AuthedSettingsGeneralRoute
  '/settings/profiles': typeof AuthedSettingsProfilesRoute
  '/settings/root-folders': typeof AuthedSettingsRootFoldersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/authors/': typeof AuthedAuthorsIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthedIndexRoute
  '/add/author': typeof AuthedAddAuthorRoute
  '/authors/$authorId': typeof AuthedAuthorsAuthorIdRoute
  '/settings/general': typeof AuthedSettingsGeneralRoute
  '/settings/profiles': typeof AuthedSettingsProfilesRoute
  '/settings/root-folders': typeof AuthedSettingsRootFoldersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/authors': typeof AuthedAuthorsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/add/author': typeof AuthedAddAuthorRoute
  '/_authed/authors/$authorId': typeof AuthedAuthorsAuthorIdRoute
  '/_authed/settings/general': typeof AuthedSettingsGeneralRoute
  '/_authed/settings/profiles': typeof AuthedSettingsProfilesRoute
  '/_authed/settings/root-folders': typeof AuthedSettingsRootFoldersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/authors/': typeof AuthedAuthorsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/add/author'
    | '/authors/$authorId'
    | '/settings/general'
    | '/settings/profiles'
    | '/settings/root-folders'
    | '/api/auth/$'
    | '/authors/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/add/author'
    | '/authors/$authorId'
    | '/settings/general'
    | '/settings/profiles'
    | '/settings/root-folders'
    | '/api/auth/$'
    | '/authors'
    | '/settings'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/'
    | '/_authed/add/author'
    | '/_authed/authors/$authorId'
    | '/_authed/settings/general'
    | '/_authed/settings/profiles'
    | '/_authed/settings/root-folders'
    | '/api/auth/$'
    | '/_authed/authors/'
    | '/_authed/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/authors/': {
      id: '/_authed/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthedAuthorsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings/root-folders': {
      id: '/_authed/settings/root-folders'
      path: '/settings/root-folders'
      fullPath: '/settings/root-folders'
      preLoaderRoute: typeof AuthedSettingsRootFoldersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/profiles': {
      id: '/_authed/settings/profiles'
      path: '/settings/profiles'
      fullPath: '/settings/profiles'
      preLoaderRoute: typeof AuthedSettingsProfilesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/general': {
      id: '/_authed/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthedSettingsGeneralRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/authors/$authorId': {
      id: '/_authed/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthedAuthorsAuthorIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/add/author': {
      id: '/_authed/add/author'
      path: '/add/author'
      fullPath: '/add/author'
      preLoaderRoute: typeof AuthedAddAuthorRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAddAuthorRoute: typeof AuthedAddAuthorRoute
  AuthedAuthorsAuthorIdRoute: typeof AuthedAuthorsAuthorIdRoute
  AuthedSettingsGeneralRoute: typeof AuthedSettingsGeneralRoute
  AuthedSettingsProfilesRoute: typeof AuthedSettingsProfilesRoute
  AuthedSettingsRootFoldersRoute: typeof AuthedSettingsRootFoldersRoute
  AuthedAuthorsIndexRoute: typeof AuthedAuthorsIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAddAuthorRoute: AuthedAddAuthorRoute,
  AuthedAuthorsAuthorIdRoute: AuthedAuthorsAuthorIdRoute,
  AuthedSettingsGeneralRoute: AuthedSettingsGeneralRoute,
  AuthedSettingsProfilesRoute: AuthedSettingsProfilesRoute,
  AuthedSettingsRootFoldersRoute: AuthedSettingsRootFoldersRoute,
  AuthedAuthorsIndexRoute: AuthedAuthorsIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
