/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as Api_testDbRouteImport } from './routes/api/__test-db'
import { Route as AuthedSystemIndexRouteImport } from './routes/_authed/system/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedBookshelfIndexRouteImport } from './routes/_authed/bookshelf/index'
import { Route as AuthedActivityIndexRouteImport } from './routes/_authed/activity/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSystemTasksRouteImport } from './routes/_authed/system/tasks'
import { Route as AuthedSystemStatusRouteImport } from './routes/_authed/system/status'
import { Route as AuthedSystemEventsRouteImport } from './routes/_authed/system/events'
import { Route as AuthedSettingsProfilesRouteImport } from './routes/_authed/settings/profiles'
import { Route as AuthedSettingsMetadataRouteImport } from './routes/_authed/settings/metadata'
import { Route as AuthedSettingsMediaManagementRouteImport } from './routes/_authed/settings/media-management'
import { Route as AuthedSettingsIndexersRouteImport } from './routes/_authed/settings/indexers'
import { Route as AuthedSettingsGeneralRouteImport } from './routes/_authed/settings/general'
import { Route as AuthedSettingsFormatsRouteImport } from './routes/_authed/settings/formats'
import { Route as AuthedSettingsDownloadClientsRouteImport } from './routes/_authed/settings/download-clients'
import { Route as AuthedBookshelfAddRouteImport } from './routes/_authed/bookshelf/add'
import { Route as AuthedActivityHistoryRouteImport } from './routes/_authed/activity/history'
import { Route as AuthedActivityBlocklistRouteImport } from './routes/_authed/activity/blocklist'
import { Route as ApiV1IndexerIndexRouteImport } from './routes/api/v1/indexer/index'
import { Route as AuthedBookshelfBooksIndexRouteImport } from './routes/_authed/bookshelf/books/index'
import { Route as AuthedBookshelfAuthorsIndexRouteImport } from './routes/_authed/bookshelf/authors/index'
import { Route as ApiV1SystemStatusRouteImport } from './routes/api/v1/system/status'
import { Route as ApiV1IndexerTestRouteImport } from './routes/api/v1/indexer/test'
import { Route as ApiV1IndexerSchemaRouteImport } from './routes/api/v1/indexer/schema'
import { Route as ApiV1IndexerIdRouteImport } from './routes/api/v1/indexer/$id'
import { Route as AuthedBookshelfBooksBookIdRouteImport } from './routes/_authed/bookshelf/books/$bookId'
import { Route as AuthedBookshelfAuthorsAuthorIdRouteImport } from './routes/_authed/bookshelf/authors/$authorId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const Api_testDbRoute = Api_testDbRouteImport.update({
  id: '/api/__test-db',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSystemIndexRoute = AuthedSystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBookshelfIndexRoute = AuthedBookshelfIndexRouteImport.update({
  id: '/bookshelf/',
  path: '/bookshelf/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivityIndexRoute = AuthedActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSystemTasksRoute = AuthedSystemTasksRouteImport.update({
  id: '/system/tasks',
  path: '/system/tasks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSystemStatusRoute = AuthedSystemStatusRouteImport.update({
  id: '/system/status',
  path: '/system/status',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSystemEventsRoute = AuthedSystemEventsRouteImport.update({
  id: '/system/events',
  path: '/system/events',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsProfilesRoute = AuthedSettingsProfilesRouteImport.update({
  id: '/settings/profiles',
  path: '/settings/profiles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsMetadataRoute = AuthedSettingsMetadataRouteImport.update({
  id: '/settings/metadata',
  path: '/settings/metadata',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsMediaManagementRoute =
  AuthedSettingsMediaManagementRouteImport.update({
    id: '/settings/media-management',
    path: '/settings/media-management',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSettingsIndexersRoute = AuthedSettingsIndexersRouteImport.update({
  id: '/settings/indexers',
  path: '/settings/indexers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsGeneralRoute = AuthedSettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsFormatsRoute = AuthedSettingsFormatsRouteImport.update({
  id: '/settings/formats',
  path: '/settings/formats',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsDownloadClientsRoute =
  AuthedSettingsDownloadClientsRouteImport.update({
    id: '/settings/download-clients',
    path: '/settings/download-clients',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBookshelfAddRoute = AuthedBookshelfAddRouteImport.update({
  id: '/bookshelf/add',
  path: '/bookshelf/add',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivityHistoryRoute = AuthedActivityHistoryRouteImport.update({
  id: '/activity/history',
  path: '/activity/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivityBlocklistRoute = AuthedActivityBlocklistRouteImport.update({
  id: '/activity/blocklist',
  path: '/activity/blocklist',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiV1IndexerIndexRoute = ApiV1IndexerIndexRouteImport.update({
  id: '/api/v1/indexer/',
  path: '/api/v1/indexer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedBookshelfBooksIndexRoute =
  AuthedBookshelfBooksIndexRouteImport.update({
    id: '/bookshelf/books/',
    path: '/bookshelf/books/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBookshelfAuthorsIndexRoute =
  AuthedBookshelfAuthorsIndexRouteImport.update({
    id: '/bookshelf/authors/',
    path: '/bookshelf/authors/',
    getParentRoute: () => AuthedRoute,
  } as any)
const ApiV1SystemStatusRoute = ApiV1SystemStatusRouteImport.update({
  id: '/api/v1/system/status',
  path: '/api/v1/system/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IndexerTestRoute = ApiV1IndexerTestRouteImport.update({
  id: '/api/v1/indexer/test',
  path: '/api/v1/indexer/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IndexerSchemaRoute = ApiV1IndexerSchemaRouteImport.update({
  id: '/api/v1/indexer/schema',
  path: '/api/v1/indexer/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IndexerIdRoute = ApiV1IndexerIdRouteImport.update({
  id: '/api/v1/indexer/$id',
  path: '/api/v1/indexer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedBookshelfBooksBookIdRoute =
  AuthedBookshelfBooksBookIdRouteImport.update({
    id: '/bookshelf/books/$bookId',
    path: '/bookshelf/books/$bookId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBookshelfAuthorsAuthorIdRoute =
  AuthedBookshelfAuthorsAuthorIdRouteImport.update({
    id: '/bookshelf/authors/$authorId',
    path: '/bookshelf/authors/$authorId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api': typeof Api_testDbRoute
  '/api/events': typeof ApiEventsRoute
  '/activity/blocklist': typeof AuthedActivityBlocklistRoute
  '/activity/history': typeof AuthedActivityHistoryRoute
  '/bookshelf/add': typeof AuthedBookshelfAddRoute
  '/settings/download-clients': typeof AuthedSettingsDownloadClientsRoute
  '/settings/formats': typeof AuthedSettingsFormatsRoute
  '/settings/general': typeof AuthedSettingsGeneralRoute
  '/settings/indexers': typeof AuthedSettingsIndexersRoute
  '/settings/media-management': typeof AuthedSettingsMediaManagementRoute
  '/settings/metadata': typeof AuthedSettingsMetadataRoute
  '/settings/profiles': typeof AuthedSettingsProfilesRoute
  '/system/events': typeof AuthedSystemEventsRoute
  '/system/status': typeof AuthedSystemStatusRoute
  '/system/tasks': typeof AuthedSystemTasksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/activity/': typeof AuthedActivityIndexRoute
  '/bookshelf/': typeof AuthedBookshelfIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/system/': typeof AuthedSystemIndexRoute
  '/bookshelf/authors/$authorId': typeof AuthedBookshelfAuthorsAuthorIdRoute
  '/bookshelf/books/$bookId': typeof AuthedBookshelfBooksBookIdRoute
  '/api/v1/indexer/$id': typeof ApiV1IndexerIdRoute
  '/api/v1/indexer/schema': typeof ApiV1IndexerSchemaRoute
  '/api/v1/indexer/test': typeof ApiV1IndexerTestRoute
  '/api/v1/system/status': typeof ApiV1SystemStatusRoute
  '/bookshelf/authors/': typeof AuthedBookshelfAuthorsIndexRoute
  '/bookshelf/books/': typeof AuthedBookshelfBooksIndexRoute
  '/api/v1/indexer/': typeof ApiV1IndexerIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api': typeof Api_testDbRoute
  '/api/events': typeof ApiEventsRoute
  '/': typeof AuthedIndexRoute
  '/activity/blocklist': typeof AuthedActivityBlocklistRoute
  '/activity/history': typeof AuthedActivityHistoryRoute
  '/bookshelf/add': typeof AuthedBookshelfAddRoute
  '/settings/download-clients': typeof AuthedSettingsDownloadClientsRoute
  '/settings/formats': typeof AuthedSettingsFormatsRoute
  '/settings/general': typeof AuthedSettingsGeneralRoute
  '/settings/indexers': typeof AuthedSettingsIndexersRoute
  '/settings/media-management': typeof AuthedSettingsMediaManagementRoute
  '/settings/metadata': typeof AuthedSettingsMetadataRoute
  '/settings/profiles': typeof AuthedSettingsProfilesRoute
  '/system/events': typeof AuthedSystemEventsRoute
  '/system/status': typeof AuthedSystemStatusRoute
  '/system/tasks': typeof AuthedSystemTasksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/activity': typeof AuthedActivityIndexRoute
  '/bookshelf': typeof AuthedBookshelfIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/system': typeof AuthedSystemIndexRoute
  '/bookshelf/authors/$authorId': typeof AuthedBookshelfAuthorsAuthorIdRoute
  '/bookshelf/books/$bookId': typeof AuthedBookshelfBooksBookIdRoute
  '/api/v1/indexer/$id': typeof ApiV1IndexerIdRoute
  '/api/v1/indexer/schema': typeof ApiV1IndexerSchemaRoute
  '/api/v1/indexer/test': typeof ApiV1IndexerTestRoute
  '/api/v1/system/status': typeof ApiV1SystemStatusRoute
  '/bookshelf/authors': typeof AuthedBookshelfAuthorsIndexRoute
  '/bookshelf/books': typeof AuthedBookshelfBooksIndexRoute
  '/api/v1/indexer': typeof ApiV1IndexerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/__test-db': typeof Api_testDbRoute
  '/api/events': typeof ApiEventsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/activity/blocklist': typeof AuthedActivityBlocklistRoute
  '/_authed/activity/history': typeof AuthedActivityHistoryRoute
  '/_authed/bookshelf/add': typeof AuthedBookshelfAddRoute
  '/_authed/settings/download-clients': typeof AuthedSettingsDownloadClientsRoute
  '/_authed/settings/formats': typeof AuthedSettingsFormatsRoute
  '/_authed/settings/general': typeof AuthedSettingsGeneralRoute
  '/_authed/settings/indexers': typeof AuthedSettingsIndexersRoute
  '/_authed/settings/media-management': typeof AuthedSettingsMediaManagementRoute
  '/_authed/settings/metadata': typeof AuthedSettingsMetadataRoute
  '/_authed/settings/profiles': typeof AuthedSettingsProfilesRoute
  '/_authed/system/events': typeof AuthedSystemEventsRoute
  '/_authed/system/status': typeof AuthedSystemStatusRoute
  '/_authed/system/tasks': typeof AuthedSystemTasksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/activity/': typeof AuthedActivityIndexRoute
  '/_authed/bookshelf/': typeof AuthedBookshelfIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/system/': typeof AuthedSystemIndexRoute
  '/_authed/bookshelf/authors/$authorId': typeof AuthedBookshelfAuthorsAuthorIdRoute
  '/_authed/bookshelf/books/$bookId': typeof AuthedBookshelfBooksBookIdRoute
  '/api/v1/indexer/$id': typeof ApiV1IndexerIdRoute
  '/api/v1/indexer/schema': typeof ApiV1IndexerSchemaRoute
  '/api/v1/indexer/test': typeof ApiV1IndexerTestRoute
  '/api/v1/system/status': typeof ApiV1SystemStatusRoute
  '/_authed/bookshelf/authors/': typeof AuthedBookshelfAuthorsIndexRoute
  '/_authed/bookshelf/books/': typeof AuthedBookshelfBooksIndexRoute
  '/api/v1/indexer/': typeof ApiV1IndexerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/api'
    | '/api/events'
    | '/activity/blocklist'
    | '/activity/history'
    | '/bookshelf/add'
    | '/settings/download-clients'
    | '/settings/formats'
    | '/settings/general'
    | '/settings/indexers'
    | '/settings/media-management'
    | '/settings/metadata'
    | '/settings/profiles'
    | '/system/events'
    | '/system/status'
    | '/system/tasks'
    | '/api/auth/$'
    | '/activity/'
    | '/bookshelf/'
    | '/settings/'
    | '/system/'
    | '/bookshelf/authors/$authorId'
    | '/bookshelf/books/$bookId'
    | '/api/v1/indexer/$id'
    | '/api/v1/indexer/schema'
    | '/api/v1/indexer/test'
    | '/api/v1/system/status'
    | '/bookshelf/authors/'
    | '/bookshelf/books/'
    | '/api/v1/indexer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/api'
    | '/api/events'
    | '/'
    | '/activity/blocklist'
    | '/activity/history'
    | '/bookshelf/add'
    | '/settings/download-clients'
    | '/settings/formats'
    | '/settings/general'
    | '/settings/indexers'
    | '/settings/media-management'
    | '/settings/metadata'
    | '/settings/profiles'
    | '/system/events'
    | '/system/status'
    | '/system/tasks'
    | '/api/auth/$'
    | '/activity'
    | '/bookshelf'
    | '/settings'
    | '/system'
    | '/bookshelf/authors/$authorId'
    | '/bookshelf/books/$bookId'
    | '/api/v1/indexer/$id'
    | '/api/v1/indexer/schema'
    | '/api/v1/indexer/test'
    | '/api/v1/system/status'
    | '/bookshelf/authors'
    | '/bookshelf/books'
    | '/api/v1/indexer'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/register'
    | '/api/__test-db'
    | '/api/events'
    | '/_authed/'
    | '/_authed/activity/blocklist'
    | '/_authed/activity/history'
    | '/_authed/bookshelf/add'
    | '/_authed/settings/download-clients'
    | '/_authed/settings/formats'
    | '/_authed/settings/general'
    | '/_authed/settings/indexers'
    | '/_authed/settings/media-management'
    | '/_authed/settings/metadata'
    | '/_authed/settings/profiles'
    | '/_authed/system/events'
    | '/_authed/system/status'
    | '/_authed/system/tasks'
    | '/api/auth/$'
    | '/_authed/activity/'
    | '/_authed/bookshelf/'
    | '/_authed/settings/'
    | '/_authed/system/'
    | '/_authed/bookshelf/authors/$authorId'
    | '/_authed/bookshelf/books/$bookId'
    | '/api/v1/indexer/$id'
    | '/api/v1/indexer/schema'
    | '/api/v1/indexer/test'
    | '/api/v1/system/status'
    | '/_authed/bookshelf/authors/'
    | '/_authed/bookshelf/books/'
    | '/api/v1/indexer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  Api_testDbRoute: typeof Api_testDbRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1IndexerIdRoute: typeof ApiV1IndexerIdRoute
  ApiV1IndexerSchemaRoute: typeof ApiV1IndexerSchemaRoute
  ApiV1IndexerTestRoute: typeof ApiV1IndexerTestRoute
  ApiV1SystemStatusRoute: typeof ApiV1SystemStatusRoute
  ApiV1IndexerIndexRoute: typeof ApiV1IndexerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/__test-db': {
      id: '/api/__test-db'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof Api_testDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/system/': {
      id: '/_authed/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof AuthedSystemIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bookshelf/': {
      id: '/_authed/bookshelf/'
      path: '/bookshelf'
      fullPath: '/bookshelf/'
      preLoaderRoute: typeof AuthedBookshelfIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activity/': {
      id: '/_authed/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof AuthedActivityIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/system/tasks': {
      id: '/_authed/system/tasks'
      path: '/system/tasks'
      fullPath: '/system/tasks'
      preLoaderRoute: typeof AuthedSystemTasksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/system/status': {
      id: '/_authed/system/status'
      path: '/system/status'
      fullPath: '/system/status'
      preLoaderRoute: typeof AuthedSystemStatusRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/system/events': {
      id: '/_authed/system/events'
      path: '/system/events'
      fullPath: '/system/events'
      preLoaderRoute: typeof AuthedSystemEventsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/profiles': {
      id: '/_authed/settings/profiles'
      path: '/settings/profiles'
      fullPath: '/settings/profiles'
      preLoaderRoute: typeof AuthedSettingsProfilesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/metadata': {
      id: '/_authed/settings/metadata'
      path: '/settings/metadata'
      fullPath: '/settings/metadata'
      preLoaderRoute: typeof AuthedSettingsMetadataRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/media-management': {
      id: '/_authed/settings/media-management'
      path: '/settings/media-management'
      fullPath: '/settings/media-management'
      preLoaderRoute: typeof AuthedSettingsMediaManagementRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/indexers': {
      id: '/_authed/settings/indexers'
      path: '/settings/indexers'
      fullPath: '/settings/indexers'
      preLoaderRoute: typeof AuthedSettingsIndexersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/general': {
      id: '/_authed/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthedSettingsGeneralRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/formats': {
      id: '/_authed/settings/formats'
      path: '/settings/formats'
      fullPath: '/settings/formats'
      preLoaderRoute: typeof AuthedSettingsFormatsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/download-clients': {
      id: '/_authed/settings/download-clients'
      path: '/settings/download-clients'
      fullPath: '/settings/download-clients'
      preLoaderRoute: typeof AuthedSettingsDownloadClientsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bookshelf/add': {
      id: '/_authed/bookshelf/add'
      path: '/bookshelf/add'
      fullPath: '/bookshelf/add'
      preLoaderRoute: typeof AuthedBookshelfAddRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activity/history': {
      id: '/_authed/activity/history'
      path: '/activity/history'
      fullPath: '/activity/history'
      preLoaderRoute: typeof AuthedActivityHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activity/blocklist': {
      id: '/_authed/activity/blocklist'
      path: '/activity/blocklist'
      fullPath: '/activity/blocklist'
      preLoaderRoute: typeof AuthedActivityBlocklistRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/v1/indexer/': {
      id: '/api/v1/indexer/'
      path: '/api/v1/indexer'
      fullPath: '/api/v1/indexer/'
      preLoaderRoute: typeof ApiV1IndexerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/bookshelf/books/': {
      id: '/_authed/bookshelf/books/'
      path: '/bookshelf/books'
      fullPath: '/bookshelf/books/'
      preLoaderRoute: typeof AuthedBookshelfBooksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bookshelf/authors/': {
      id: '/_authed/bookshelf/authors/'
      path: '/bookshelf/authors'
      fullPath: '/bookshelf/authors/'
      preLoaderRoute: typeof AuthedBookshelfAuthorsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/v1/system/status': {
      id: '/api/v1/system/status'
      path: '/api/v1/system/status'
      fullPath: '/api/v1/system/status'
      preLoaderRoute: typeof ApiV1SystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/indexer/test': {
      id: '/api/v1/indexer/test'
      path: '/api/v1/indexer/test'
      fullPath: '/api/v1/indexer/test'
      preLoaderRoute: typeof ApiV1IndexerTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/indexer/schema': {
      id: '/api/v1/indexer/schema'
      path: '/api/v1/indexer/schema'
      fullPath: '/api/v1/indexer/schema'
      preLoaderRoute: typeof ApiV1IndexerSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/indexer/$id': {
      id: '/api/v1/indexer/$id'
      path: '/api/v1/indexer/$id'
      fullPath: '/api/v1/indexer/$id'
      preLoaderRoute: typeof ApiV1IndexerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/bookshelf/books/$bookId': {
      id: '/_authed/bookshelf/books/$bookId'
      path: '/bookshelf/books/$bookId'
      fullPath: '/bookshelf/books/$bookId'
      preLoaderRoute: typeof AuthedBookshelfBooksBookIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bookshelf/authors/$authorId': {
      id: '/_authed/bookshelf/authors/$authorId'
      path: '/bookshelf/authors/$authorId'
      fullPath: '/bookshelf/authors/$authorId'
      preLoaderRoute: typeof AuthedBookshelfAuthorsAuthorIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedActivityBlocklistRoute: typeof AuthedActivityBlocklistRoute
  AuthedActivityHistoryRoute: typeof AuthedActivityHistoryRoute
  AuthedBookshelfAddRoute: typeof AuthedBookshelfAddRoute
  AuthedSettingsDownloadClientsRoute: typeof AuthedSettingsDownloadClientsRoute
  AuthedSettingsFormatsRoute: typeof AuthedSettingsFormatsRoute
  AuthedSettingsGeneralRoute: typeof AuthedSettingsGeneralRoute
  AuthedSettingsIndexersRoute: typeof AuthedSettingsIndexersRoute
  AuthedSettingsMediaManagementRoute: typeof AuthedSettingsMediaManagementRoute
  AuthedSettingsMetadataRoute: typeof AuthedSettingsMetadataRoute
  AuthedSettingsProfilesRoute: typeof AuthedSettingsProfilesRoute
  AuthedSystemEventsRoute: typeof AuthedSystemEventsRoute
  AuthedSystemStatusRoute: typeof AuthedSystemStatusRoute
  AuthedSystemTasksRoute: typeof AuthedSystemTasksRoute
  AuthedActivityIndexRoute: typeof AuthedActivityIndexRoute
  AuthedBookshelfIndexRoute: typeof AuthedBookshelfIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedSystemIndexRoute: typeof AuthedSystemIndexRoute
  AuthedBookshelfAuthorsAuthorIdRoute: typeof AuthedBookshelfAuthorsAuthorIdRoute
  AuthedBookshelfBooksBookIdRoute: typeof AuthedBookshelfBooksBookIdRoute
  AuthedBookshelfAuthorsIndexRoute: typeof AuthedBookshelfAuthorsIndexRoute
  AuthedBookshelfBooksIndexRoute: typeof AuthedBookshelfBooksIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedActivityBlocklistRoute: AuthedActivityBlocklistRoute,
  AuthedActivityHistoryRoute: AuthedActivityHistoryRoute,
  AuthedBookshelfAddRoute: AuthedBookshelfAddRoute,
  AuthedSettingsDownloadClientsRoute: AuthedSettingsDownloadClientsRoute,
  AuthedSettingsFormatsRoute: AuthedSettingsFormatsRoute,
  AuthedSettingsGeneralRoute: AuthedSettingsGeneralRoute,
  AuthedSettingsIndexersRoute: AuthedSettingsIndexersRoute,
  AuthedSettingsMediaManagementRoute: AuthedSettingsMediaManagementRoute,
  AuthedSettingsMetadataRoute: AuthedSettingsMetadataRoute,
  AuthedSettingsProfilesRoute: AuthedSettingsProfilesRoute,
  AuthedSystemEventsRoute: AuthedSystemEventsRoute,
  AuthedSystemStatusRoute: AuthedSystemStatusRoute,
  AuthedSystemTasksRoute: AuthedSystemTasksRoute,
  AuthedActivityIndexRoute: AuthedActivityIndexRoute,
  AuthedBookshelfIndexRoute: AuthedBookshelfIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSystemIndexRoute: AuthedSystemIndexRoute,
  AuthedBookshelfAuthorsAuthorIdRoute: AuthedBookshelfAuthorsAuthorIdRoute,
  AuthedBookshelfBooksBookIdRoute: AuthedBookshelfBooksBookIdRoute,
  AuthedBookshelfAuthorsIndexRoute: AuthedBookshelfAuthorsIndexRoute,
  AuthedBookshelfBooksIndexRoute: AuthedBookshelfBooksIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  Api_testDbRoute: Api_testDbRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1IndexerIdRoute: ApiV1IndexerIdRoute,
  ApiV1IndexerSchemaRoute: ApiV1IndexerSchemaRoute,
  ApiV1IndexerTestRoute: ApiV1IndexerTestRoute,
  ApiV1SystemStatusRoute: ApiV1SystemStatusRoute,
  ApiV1IndexerIndexRoute: ApiV1IndexerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
